# Generated by Django 4.2.3 on 2024-08-31 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_alter_ledger_code_alter_ledgertype_code_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="generaljournal",
            unique_together=set(),
        ),
    ]
