# Generated by Django 4.2.3 on 2024-09-18 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_alter_user_groups_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thana",
            name="district",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="Division",
        ),
        migrations.DeleteModel(
            name="Thana",
        ),
    ]
