# Generated by Django 4.2.3 on 2025-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_team_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
