# Generated by Django 5.2.1 on 2025-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(default="abc@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
