# Generated by Django 4.2.7 on 2026-04-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_cihcalculation_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CIHCalculation',
        ),
    ]
