# Generated by Django 4.2.3 on 2024-10-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0001_initial"),
        ("transaction", "0004_transactionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loan.loanreason",
            ),
        ),
    ]
