# Generated by Django 4.2.7 on 2026-05-01 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0003_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0006_branch_is_active'),
        ('transaction', '0005_loanreason_loan_loan_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_amount', models.IntegerField(default=0)),
                ('total_installment', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.loanreason')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peoples.member')),
            ],
            options={
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['branch', 'status', 'position'], name='transaction_branch__10a0f5_idx')],
            },
        ),
    ]
