# Generated by Django 4.2.3 on 2024-09-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_alter_user_groups_alter_user_is_superuser"),
        ("peoples", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="member",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="members",
                to="organization.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("team", "serial_number", "is_active")},
        ),
    ]
