# Generated by Django 4.2.3 on 2025-06-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peoples", "0002_alter_member_unique_together_alter_member_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
